version: 2
jobs:
  build:
    docker:
      - image: ciandt/gulp
    steps:
      - checkout
      - run: npm install
      - run: npm install gulp
      - run: gulp build-loc
    artifacts:
      paths:
        - dist/
      expire_in: 1 hour
    only:
      - master