version: 2
jobs:
  build:
    docker:
    - image: ciandt/gulp
    steps:
    - checkout
    - run: npm install
    - run: gulp build-loc
    - persist_to_workspace:
        root: /workspace
        paths:
        - dist
  deploy:
    docker:
    - image: circleci/python:2.7-jessie

    steps:
    - attach_workspace:
        at: /workspace
    - run:
        name: Check directory
        command: ls
    - run:
        name: Install AWS
        command: sudo pip install awscli
    - run:
        name: Deploy to s3
        command: aws s3 sync workspace/dist s3://${S3_BUCKET} --delete

workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master